name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

env:
  RACK_SDK_VERSION: 2.6.4

jobs:
  buildLinux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Linux
        uses: ./.github/actions/build_linux
      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Upload asset to release
        run: sh ./.github/actions/upload_zip/script.sh ${{ secrets.GITHUB_TOKEN }}

  buildWindows:
    name: Build Windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Windows
        uses: ./.github/actions/build_win
      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Upload asset to release
        run: sh ./.github/actions/upload_zip/script.sh ${{ secrets.GITHUB_TOKEN }}

  buildOsx:
    name: Build macOS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build macOS
        uses: ./.github/actions/build_osx
      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Upload asset to release
        run: sh ./.github/actions/upload_zip/script.sh ${{ secrets.GITHUB_TOKEN }}

  combineDist:
    name: Combine Distributions
    runs-on: ubuntu-latest
    needs: [buildLinux, buildWindows, buildOsx]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y jq unzip zip
      - name: Combine and upload
        run: sh ./.github/actions/combine_zip/script.sh ${{ secrets.GITHUB_TOKEN }}
