name: Development

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  RACK_SDK_VERSION: 2.6.4

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Linux
        uses: ./.github/actions/build_linux

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-linux
          path: dist/*.zip
